variables:
  DotNetCoreSdkVersion: '7.0.100-preview.5.22307.18'
  NUGET_PACKAGES: '$(Pipeline.Workspace)/.nuget/packages'

jobs:
- job: linux_build
  displayName: 'Linux Build'
  pool:
    vmimage: 'ubuntu-20.04'
  steps:
  - template: '.ci/build-steps.yml'

- job: windows_build
  displayName: 'Windows Build'
  pool:
    vmimage: 'windows-latest'
  steps:
  - template: '.ci/build-steps.yml'
  - task: DotNetCoreCLI@2
    displayName: 'Publish SideBySide (net472)'
    inputs:
      command: 'publish'
      arguments: '-c Release -f net472 tests/SideBySide/SideBySide.csproj'
      publishWebProjects: false
      zipAfterPublish: false
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'SideBySide-net472-$(Agent.OS)'
      targetPath: 'tests/SideBySide/bin/Release/net472/publish'

- job: windows_baseline
  displayName: 'Baseline'
  pool:
    vmimage: 'windows-2019'
  steps:
  - template: '.ci/install-mysql-windows.yml'
  - task: CopyFiles@2
    displayName: 'Copy config.json'
    inputs:
      sourceFolder: '.ci/config'
      contents: 'config.json'
      targetFolder: 'tests/SideBySide'
  - task: UseDotNet@2
    displayName: 'Install .NET Core 6.0'
    inputs:
      version: '6.0.x'
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: $(DotNetCoreSdkVersion)
  - task: DotNetCoreCLI@2
    displayName: 'Unit tests'
    inputs:
      command: 'test'
      arguments: 'tests\MySqlConnector.Tests\MySqlConnector.Tests.csproj -c Baseline'
      testRunTitle: 'Baseline unit tests'
  - task: DotNetCoreCLI@2
    displayName: 'Baseline tests'
    inputs:
      command: 'test'
      arguments: 'tests\SideBySide\SideBySide.csproj -c Baseline'
      testRunTitle: 'Baseline tests'
    env:
      DATA__UNSUPPORTEDFEATURES: 'Ed25519,QueryAttributes,UnixDomainSocket'
      DATA__CONNECTIONSTRING: 'server=localhost;port=3306;user id=root;password=test;database=mysqltest;ssl mode=none;DefaultCommandTimeout=3600'
      DATA__CERTIFICATESPATH: '$(Build.Repository.LocalPath)\.ci\server\certs\'
      DATA__MYSQLBULKLOADERLOCALCSVFILE: '$(Build.Repository.LocalPath)\tests\TestData\LoadData_UTF8_BOM_Unix.CSV'
      DATA__MYSQLBULKLOADERLOCALTSVFILE: '$(Build.Repository.LocalPath)\tests\TestData\LoadData_UTF8_BOM_Unix.TSV'
      TF_BUILD: $(TF_BUILD)
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: 'Baseline Tests'
      failTaskOnFailedTests: true

- job: linux_unit_tests
  dependsOn: linux_build
  displayName: 'Linux Unit Tests'
  pool:
    vmimage: 'ubuntu-20.04'
  steps:
  - template: '.ci/mysqlconnector-tests-steps.yml'

- job: windows_unit_tests
  dependsOn: windows_build
  displayName: 'Windows Tests'
  pool:
    vmimage: 'windows-2019'
  steps:
  - template: '.ci/install-mysql-windows.yml'
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1'
    inputs:
      version: 3.1.x
      packageType: runtime
  - template: '.ci/mysqlconnector-tests-steps.yml'
  - template: '.ci/conformance-test-steps.yml'
    parameters:
      image: 'mysql:8.0'
      connectionString: 'server=localhost;port=3306;user id=mysqltest;password=test;database=conformance;ssl mode=none;DefaultCommandTimeout=3600;AllowPublicKeyRetrieval=True'

- job: azure_mysql_integration_tests
  condition: ne('True', variables['System.PullRequest.IsFork'])
  displayName: 'Azure MySQL Integration Tests'
  pool:
    vmimage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 6.0'
    inputs:
      version: 6.0.x
      packageType: runtime
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: $(DotNetCoreSdkVersion)
  - task: PowerShell@2
    displayName: 'Copy Azure config'
    inputs:
      targetType: inline
      script: Copy-Item -Path ".\.ci\config\config.ssl.json" -Destination ".\tests\SideBySide\config.json"
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
  - task: DotNetCoreCLI@2
    displayName: 'Side by Side tests (net6.0)'
    inputs:
      command: 'test'
      projects: 'tests/SideBySide/SideBySide.csproj'
      arguments: '-c Release -f net6.0 --no-restore'
      testRunTitle: ${{ format('{0}, $(Agent.OS), {1}, {2}', 'Azure', 'net6.0', 'SSL') }}
    env:
      DATA__UNSUPPORTEDFEATURES: 'CachingSha2Password,Ed25519,GlobalLog,KnownCertificateAuthority,QueryAttributes,RsaEncryption,Sha256Password,Timeout,Tls11,Tls13,UnixDomainSocket,ZeroDateTime'
      DATA__CONNECTIONSTRING: "$(AzureConnectionString);database=mysqltest;ssl mode=Required;DefaultCommandTimeout=3600;AllowPublicKeyRetrieval=True"

- job: windows_integration_tests_1
  displayName: 'Windows Integration Tests (Part 1)'
  pool:
    vmimage: 'windows-2019'
  steps:
  - template: '.ci/install-mysql-windows.yml'
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: $(DotNetCoreSdkVersion)
  - task: CopyFiles@2
    displayName: 'Copy config.json'
    inputs:
      sourceFolder: '.ci/config'
      contents: 'config.json'
      targetFolder: 'tests/SideBySide'
  - task: PowerShell@2
    displayName: 'Remove target frameworks'
    inputs:
      targetType: 'inline'
      script: '((Get-Content .\tests\SideBySide\SideBySide.csproj -Raw) -replace(''<TargetFrameworks>.*</TargetFrameworks>'', ''<TargetFrameworks>net472;net7.0</TargetFrameworks>'')) | Set-Content .\tests\SideBySide\SideBySide.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
  - task: DotNetCoreCLI@2
    displayName: 'Side by Side tests (net472/net7.0)'
    inputs:
      command: 'test'
      projects: 'tests/SideBySide/SideBySide.csproj'
      arguments: '-c Release --no-restore'
      testRunTitle: ${{ format('{0}, $(Agent.OS), {1}, {2}', 'mysql:8.0', 'net472/net7.0', 'No SSL') }}
    env:
      DATA__UNSUPPORTEDFEATURES: 'Ed25519,QueryAttributes,Tls11,UnixDomainSocket'
      DATA__CONNECTIONSTRING: 'server=localhost;port=3306;user id=mysqltest;password=test;database=mysqltest;ssl mode=none;DefaultCommandTimeout=3600;AllowPublicKeyRetrieval=True;UseCompression=True'

- job: windows_integration_tests_2
  displayName: 'Windows Integration Tests (Part 2)'
  pool:
    vmimage: 'windows-2019'
  steps:
  - template: '.ci/install-mysql-windows.yml'
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1'
    inputs:
      version: 3.1.x
      packageType: runtime
  - task: UseDotNet@2
    displayName: 'Install .NET Core 6.0'
    inputs:
      version: 6.0.x
      packageType: runtime
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: $(DotNetCoreSdkVersion)
  - script: copy .ci\config\config.json tests\SideBySide\config.json
    displayName: 'Copy config.json'
  - task: PowerShell@2
    displayName: 'Remove target frameworks'
    inputs:
      targetType: 'inline'
      script: '((Get-Content .\tests\SideBySide\SideBySide.csproj -Raw) -replace(''<TargetFrameworks>.*</TargetFrameworks>'', ''<TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>'')) | Set-Content .\tests\SideBySide\SideBySide.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: 'restore'
  - task: DotNetCoreCLI@2
    displayName: 'Side by Side tests (netcoreapp3.1/net6.0)'
    inputs:
      command: 'test'
      projects: 'tests/SideBySide/SideBySide.csproj'
      arguments: '-c Release --no-restore'
      testRunTitle: ${{ format('{0}, $(Agent.OS), {1}, {2}', 'mysql:8.0', 'netcoreapp3.1/net6.0', 'No SSL') }}
    env:
      DATA__UNSUPPORTEDFEATURES: 'Ed25519,QueryAttributes,Tls11,UnixDomainSocket'
      DATA__CONNECTIONSTRING: 'server=localhost;port=3306;user id=mysqltest;password=test;database=mysqltest;ssl mode=none;DefaultCommandTimeout=3600;AllowPublicKeyRetrieval=True'

- job: linux_integration_tests
  dependsOn: linux_build
  displayName: 'Linux Tests'
  pool:
    vmimage: 'ubuntu-20.04'
  strategy:
    matrix:
      'MySQL 5.6':
        image: 'mysql:5.6'
        unsupportedFeatures: 'CachingSha2Password,Ed25519,Json,LargePackets,QueryAttributes,ResetConnection,SessionTrack,Sha256Password,Tls11,Tls13,UuidToBin'
      'MySQL 5.7':
        image: 'mysql:5.7'
        unsupportedFeatures: 'CachingSha2Password,Ed25519,QueryAttributes,Tls11,Tls13,UuidToBin'
      'MySQL 8.0':
        image: 'mysql:8.0'
        unsupportedFeatures: 'Ed25519,Tls11,ZeroDateTime'
      'MariaDB 10.4':
        image: 'mariadb:10.4'
        unsupportedFeatures: 'CachingSha2Password,Json,RoundDateTime,QueryAttributes,Sha256Password,Tls11,UuidToBin'
      'MariaDB 10.5':
        image: 'mariadb:10.5'
        unsupportedFeatures: 'CachingSha2Password,Json,RoundDateTime,QueryAttributes,Sha256Password,Tls11,UuidToBin'
      'MariaDB 10.6':
        image: 'mariadb:10.6'
        unsupportedFeatures: 'CachingSha2Password,Json,RoundDateTime,QueryAttributes,Sha256Password,Tls11,UuidToBin'
  steps:
  - template: '.ci/integration-tests-steps.yml'
    parameters:
      image: $(image)
      unsupportedFeatures: $(unsupportedFeatures)
      DotNetCoreSdkVersion: $(DotNetCoreSdkVersion)
