title = "High-Performance .NET MySQL Driver"
baseurl = "https://mysqlconnector.net/"
MetaDataFormat = "yaml"
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "friendly"
disablePathToLower = true

[blackfriday]
  plainIDAnchors = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "MySqlConnector is a high-performance, asynchronous C# ADO.NET driver for MySQL Server, MariaDB, Amazon Aurora, Azure Database for MySQL, Google Cloud SQL for MySQL, Percona Server and more."
  author = "MySqlConnector Authors"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = 20
[[menu.main]]
    name = "API"
    identifier = "api"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/api/MySqlConnectorAssembly/"
    weight = 30
[[menu.main]]
    name = "Diagnostics"
    identifier = "diagnostics"
    pre = "<i class='fa fa-road'></i>"
    weight = 40
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-lightbulb-o'></i>"
    weight = 50
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-lightbulb-o'></i>"
    weight = 60
